
[[sec_5]]
== Data product identification

This clause describes how to identify data sets that conform to the
specification. A dataset that conforms to this Product Specification
may be identified by its discovery metadata as defined in <<sec_12>>
of this specification. The information identifying the data product
may include the following items from <<IHO_S_100,clause=11-6>>
(adapted from <<ISO_19115_1>>).

*title*:: Marine Traffic Management

*abstract*:: Marine Traffic Management dataset is a vector dataset
containing all maritime navigationally relevant information regarding
the traffic management within a defined geographical area.

*alternate title*:: MTM

*content*:: Marine Traffic Management information, such as the availability
and reliability of vessel traffic services, pilotage, routing measures,
and ship reporting systems. This includes their service areas, services
offered, and instructions for contacting or utilizing these services.

*geographicDescription*:: *EX_GeographicDescription:* E.g., official
name of region

*spatialResolution*:: MD_Resolution>equivalentScale.denominator (integer)
or MD_Resolution>levelOfDetail (CharacterString). E.g.: "All scales"

*purpose*:: Describing traffic management in the maritime domain for
utilization in ECDIS, and to allow the producer to exchange Marine
Traffic Management information with interested stakeholders.

*language*:: ENAdditional values, if any, use CharacterString values
from <<ISO_639_2>>
