

[[sec_8]]
== Coordinate reference system (CRS)

[[sec_8.1]]
=== Introduction

The location of an object in the S-100 standard is defined by means
of coordinates which relate a feature to a position. The coordinate
reference system used for this product specification is World Geodetic
System 1984 (WGS 84) which is defined by the European Petroleum Survey
Group (EPSG) code 4326, (or similar - North American Datum 1983 /
Canadian Spatial Reference System).

Spatial data are expressed as latitude (stem:[varphi]) and longitude
(stem:[lambda]) geographic
coordinates. Latitude values are stored as a negative number to represent
a position south of the Equator. Longitude values are stored as a
negative number to represent a position west of the Prime Meridian.
Coordinates are expressed as real value, degree / degree decimal format.
Datasets conforming to this product specification are not projected.

*Horizontal coordinate reference system:*:: WGS 84

*Projection:*:: None

*Vertical coordinate reference system:*:: None footnote:[Not used
in any of the feature classes, therefore not needed.]

*Temporal reference system:*:: Gregorian calendar

*Coordinate reference system registry:*:: http://www.epsg-registry.org/[EPSG Geodetic Parameter Registry]

*Date type (according to <<ISO_19115_1>>):*:: 002 - publication

[[sec_8.2]]
=== Horizontal reference system

Positional data is expressed in latitude and longitude geographic
coordinates to one of the reference horizontal reference systems defined
in the HORDAT attribute. Unless otherwise defined, the World Geodetic
System 84 (WGS 84) will be used for MTM data products.

[[sec_8.3]]
=== Projection

Marine Traffic Management data products are un-projected.

[[sec_8.4]]
=== Vertical coordinate reference system

Marine Traffic Management data products do not provide detailed vertical
information.

[[sec_8.5]]
=== Temporal reference system

Time is measured by reference to Calendar dates and Clock time in
accordance with <<ISO_19108_2002,clause=5.4.4>>, Temporal Schema.

[[sec_8.6]]
=== Marine Traffic Management data and scale

MTM data must be compiled in the best applicable scale. The use of
the data itself is "scale independent". That means that the data can
be used at any scale. S-100 allows the association of multiple spatial
attributes to a single feature instance. In principle, each of these
spatial attributes can be qualified by maximum and minimum scales.

For example, it is possible, within one dataset, to have a single
instance of a feature that has more than one area geometry. Each of
these geometries has different scale max/min attributes. Moreover,
due to cluttering in smaller scales, the scale minimum attribute may
be used to turn off portrayal of some features at smaller scales.
