
[[sec_10]]
== Data capture and classification

Data source: S-127 products must be based on data sources released
by an appropriate MTM defining authority. Data source must be described
in each data product.

The production process used to generate MTM products may be described
in the comment attribute of the dataset metadata.

[[sec_10.1]]
=== Data encoding and product delivery

[[sec_10.1.1]]
==== Data encoding

The principal encoding will be the Open Geospatial Consortium (OGC),
Geography Markup Language (GML) format. GML is an XML grammar designed
to express geographical features. It serves as a modelling language
for geographic systems as well as an open interchange format for geographic
transactions.

[[sec_10.1.2]]
==== Types of datasets

A dataset is a grouping of features, attributes, geometry and metadata
which comprises a specific coverage. <<table_10.1>> lists the types
of MTM datasets which may be produced and contained within an exchange
set:

[[table_10.1]]
.MTM dataset types
[cols="21,44"]
|===
h| Dataset h| Explanations

| New dataset (base dataset)
| Data for an area different (in coverage and/or extent) to existing
datasets.

| New Edition of a dataset
| A re-issue plus new information which has not been previously distributed
by Updates. Each New Edition of a dataset must have the same name
as the dataset that it replaces and should have the same spatial extents.
The edition number in the dataset discovery metadata must increment
up by one from the previous edition.

| Update dataset
| A delta change of the latest edition of a dataset. If there is more
than one update dataset, the subsequent update will be a delta of
the base dataset + earlier update datasets.

| Cancellation | Used to cancel dataset and any related update datasets.

|===

[[sec_10.1.3]]
==== Content of update datasets

Update datasets can only contain replacements, deletions, and additions
of whole feature instances or information instances. This means that
when a feature or information instance is updated, the new version
must contain all the attributes of the old instance, including any
inline spatial attributes (i.e., inline geometry), except those attributes
that are being removed.

An association to an instance of a feature or information type is
treated as an attribute of the referring instance, and therefore adding
or deleting an association means the original referring instance must
be replaced with a new version. The instance at the other end of the
association needs to be replaced if and only if it contains a reference
to the first instance.

Spatial objects that are not inline (i.e., geometry that is encoded
as an independent spatial object in the dataset) is treated like any
other object, i.e., it needs to be updated if and only if the primitive
has changed (e.g., a coordinate is updated).

Feature and information type instances are deleted without replacement
by setting the fixedDateRange.dateEnd attribute of the instance to
the date of deletion, which will usually be the issue date of the
update.

[[sec_10.2]]
=== Encoding of latitude and longitude

Values of latitude and longitude must be accurate to 7 decimal places.
Coordinates must be encoded as decimals in the format described in
<<sec_10.2.1>>. The encoding is indicated by multiplication factor
fields defined in the dataset identification record.

[[sec_10.2.1]]
==== Encoding of coordinates as decimals

Values should be coded as decimal numbers with 7 or fewer digits after
the decimal. The normative encoding is in degrees, with an accuracy
of stem:[10^{-7}] degrees, i.e., 7 digits after the decimal point.

The decimal point must be indicated by the "." character.

Trailing zeroes after the decimal point (and the decimal point itself
if appropriate) may be omitted at producer discretion, but the accuracy
must still be as indicated (e.g., stem:[10^{-7}] degrees for coordinates
of default accuracy).

Latitude and longitude multiplication factors held in the Dataset
Structure Information field under [coordMultFactorX] and [coordMultFactorY]
must be set to a value corresponding to the encoding, i.e., {1} for
coordinates encoded in decimal degrees.

[example]
A stem:["longitude" = 42.0000] is converted into
stem:[X = "longitude" * "coordMultFactorX" = 42.0000 * 1 = 42.0000000].

[[sec_10.3]]
=== Numeric attribute encoding

Floating point and integer attribute values must not contain leading
zeros. Floating point attribute values must not contain non-significant
trailing zeros.

[[sec_10.4]]
=== Text attribute values

Character strings must be encoded using the character set defined
in <<ISO_10646_1>>, in Unicode Transformation Format-8 (UTF-8).

[[sec_10.5]]
=== Mandatory attribute values

There are four reasons why attribute values may be considered mandatory:

* They determine whether a feature is in the display base,
* Certain features make no logical sense without specific attributes,
* Some attributes are necessary to determine which symbol is to be
displayed,
* Some attributes are required for safety of navigation.

All mandatory attributes are identified in the Feature Catalogue and
summarised in <<S127AnnexA>>.

[[sec_10.6]]
=== Unknown attribute values

When a mandatory attribute code or tag is present but the attribute
value is missing, it means that the producer wishes to indicate that
this attribute value is unknown. Missing mandatory attributes must
be "nilled."

Optional attributes must be omitted altogether if the value is unknown
or missing. They must not be "nilled."

=====
A landmark feature has unknown category of landmark (mandatory attribute)
and function (optional attribute). The feature could be coded as:

[source]
--
<Landmark>
  <categoryOfLandmark xsi:nil="true"/>
  <function>radio</function>
  ... other attributes...
  ... <status> is NOT coded ...
<Landmark>
--
=====

[[sec_10.7]]
=== Structure of dataset files

// left it here

[[sec_10.7.1]]
==== Sequence of objects

The order of data objects in each dataset file is described below:

[pseudocode%unnumbered]
====
    Dataset Identification Information
    Dataset structure information
    Spatial records for by-reference geometries
        Point
        Multi point
        Curve
        Composite Curve
        Surface
    Information objects
    Feature objects (Geometry may be encoded inline or by reference.)
    Meta features
    Geo features
====

[[sec_10.8]]
=== Object identifiers

The "name" of feature records must provide a unique world-wide identifier
of feature records. The "name" of the record is the combination of
the subfields *agency*, *featureObjectIdentifier*, and
*featureIdentificationSubdivision* elements of the *featureObjectIdentifier*
element of the object.

Features, information types, collection objects, meta features, and
geometries (inline or external) are all required by the schema to
have a *gml:id* attribute with a value that is unique within the dataset.
The *gml:id* values must be used as the reference for the object from
another object in the same dataset or another dataset.

MRN identifiers are not included in this version due to ongoing development
of the IHO guidelines in the use of MRN for product specifications.

[[sec_10.9]]
=== Data coverage

All areas of a dataset must be covered by a *DataCoverage* meta feature.

An update dataset must not change the limit of a *Data Coverage* feature
for the base dataset. Where the limit of a *Data Coverage* feature
for a base dataset is to be changed, this must be done by issuing
a new edition of the dataset.

[[sec_10.10]]
=== Data overlap

S-127 datasets must not overlap other S-127 datasets.

[[sec_10.11]]
=== Data quality

One or more *QualityOfNonBathymetricData* features must cover the
dataset.

[[sec_10.12]]
=== Data extent

Datasets must not cross the stem:[180 "unitsml(deg)"] meridian of longitude
